# Subsets for Control Removal
I am going to resubset our cleaned full data.

In [17]:
import pandas as pd
import numpy as np

In [18]:
endo = pd.read_csv("../../data/genbank/full_data.csv")

In [19]:
endo = endo.drop(endo.columns[0], axis=1)

In [20]:
endo.head()

,sample,tissue,endometriosis,severity,probe_1007_s_at,TTLL12,TMEM106A,C4orf33,GAMT,LACTB,...,GS1-124K5.4,probe_239901_at,TPBG.1,probe_239907_at,CCDC142,probe_239923_at,GALNT2.1,GNG11.1,probe_239946_at,ZNF160.2
0,GSM1256653,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.142574,7.511474,6.104687,6.448481,4.083183,4.290113,...,6.089663,4.718174,2.870847,4.133619,4.087568,3.401581,5.512515,5.817085,4.076473,6.146053
1,GSM1256654,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.063049,8.031766,3.587175,6.712542,3.782646,4.301305,...,4.949523,4.398681,3.206235,3.064746,3.817188,3.500782,5.443936,4.141156,2.708966,6.163275
2,GSM1256655,Proliferative Endometrial tissue,Endometriosis,Moderate/Severe,8.371274,7.793815,4.619336,5.053898,3.778297,3.994715,...,4.592546,5.932227,4.433987,4.133619,4.928141,3.401581,4.725973,3.261094,2.722704,4.890128
3,GSM1256656,Mid-Secretory Endometrial tissue,Endometriosis,Moderate/Severe,10.328161,10.330194,4.498046,3.362764,4.346867,4.740147,...,4.464066,6.504075,4.001146,4.869423,2.883428,3.401581,4.816648,2.998406,2.950739,5.365149
4,GSM1256657,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.053309,8.786554,5.463671,5.649013,4.982704,3.994715,...,4.464066,4.696087,4.748566,4.134441,3.903931,3.640835,4.725973,3.954060,4.144242,4.458397

In [21]:
endo.shape

(148, 14855)

In [22]:
endo.shape[1]-4

14851

In [23]:
ranges = [[np.min(x), np.max(x)] for x in [range(y*(endo.shape[1]-4)/10,(y+1)*(endo.shape[1]-4)/10) for y in range(0,10)]]
ranges

[[0, 1484],
 [1485, 2969],
 [2970, 4454],
 [4455, 5939],
 [5940, 7424],
 [7425, 8909],
 [8910, 10394],
 [10395, 11879],
 [11880, 13364],
 [13365, 14850]]

In [24]:
# ranges[len(ranges)-1][1] = ranges[len(ranges)-1][1]+1

In [25]:
ranges = pd.DataFrame(ranges, columns=["start", "end"])
ranges

   start    end
0      0   1484
1   1485   2969
2   2970   4454
3   4455   5939
4   5940   7424
5   7425   8909
6   8910  10394
7  10395  11879
8  11880  13364
9  13365  14850

All of these indices are off by "a count of 4". These four columns will be included in all subsets.

In [26]:
meta = endo[endo.columns[0:4]]
meta.head()

,sample,tissue,endometriosis,severity
0,GSM1256653,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe
1,GSM1256654,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe
2,GSM1256655,Proliferative Endometrial tissue,Endometriosis,Moderate/Severe
3,GSM1256656,Mid-Secretory Endometrial tissue,Endometriosis,Moderate/Severe
4,GSM1256657,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe

In [27]:
this_range = range(list(ranges.iloc[0])[0], list(ranges.iloc[0])[1])
this_cut   = endo[endo.columns[[x+4 for x in this_range]]]
this_cut.head()

,probe_1007_s_at,TTLL12,TMEM106A,C4orf33,GAMT,LACTB,SH2D3C,CASC4,EXOC3L2,MMEL1,...,ALDOA,PPIB,PPIB.1,SERP1,TSPAN3,TSPAN3.1,ACTA2,TAX1BP1,MDH1,GNAS.1
0,9.142574,7.511474,6.104687,6.448481,4.083183,4.290113,4.581217,3.038863,6.587117,4.484573,...,13.081686,14.567154,14.035357,11.723501,11.764844,10.120559,11.498782,9.803481,11.933551,14.221893
1,9.063049,8.031766,3.587175,6.712542,3.782646,4.301305,4.587505,2.850773,5.998291,5.205437,...,13.221184,14.090926,14.070026,11.930866,11.721171,11.734594,10.977257,9.702074,12.359035,14.190868
2,8.371274,7.793815,4.619336,5.053898,3.778297,3.994715,4.713673,3.335726,7.440760,4.014491,...,12.291971,13.930689,13.348895,10.938431,10.992398,10.514306,13.587959,10.040062,11.173445,13.705868
3,10.328161,10.330194,4.498046,3.362764,4.346867,4.740147,4.637108,4.527306,6.587117,3.561544,...,13.370437,14.324211,14.355933,11.283750,10.678844,9.513877,13.009815,10.091932,10.676529,13.825387
4,9.053309,8.786554,5.463671,5.649013,4.982704,3.994715,4.736653,2.850773,6.587117,4.060130,...,13.112724,14.104104,13.644645,11.725484,11.967791,11.433822,12.062999,9.794262,11.955416,14.020896

In [28]:
this_subset = meta.join(this_cut, how="outer")
this_subset.head()

,sample,tissue,endometriosis,severity,probe_1007_s_at,TTLL12,TMEM106A,C4orf33,GAMT,LACTB,...,ALDOA,PPIB,PPIB.1,SERP1,TSPAN3,TSPAN3.1,ACTA2,TAX1BP1,MDH1,GNAS.1
0,GSM1256653,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.142574,7.511474,6.104687,6.448481,4.083183,4.290113,...,13.081686,14.567154,14.035357,11.723501,11.764844,10.120559,11.498782,9.803481,11.933551,14.221893
1,GSM1256654,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.063049,8.031766,3.587175,6.712542,3.782646,4.301305,...,13.221184,14.090926,14.070026,11.930866,11.721171,11.734594,10.977257,9.702074,12.359035,14.190868
2,GSM1256655,Proliferative Endometrial tissue,Endometriosis,Moderate/Severe,8.371274,7.793815,4.619336,5.053898,3.778297,3.994715,...,12.291971,13.930689,13.348895,10.938431,10.992398,10.514306,13.587959,10.040062,11.173445,13.705868
3,GSM1256656,Mid-Secretory Endometrial tissue,Endometriosis,Moderate/Severe,10.328161,10.330194,4.498046,3.362764,4.346867,4.740147,...,13.370437,14.324211,14.355933,11.283750,10.678844,9.513877,13.009815,10.091932,10.676529,13.825387
4,GSM1256657,Early Secretory Endometrial tissue,Endometriosis,Moderate/Severe,9.053309,8.786554,5.463671,5.649013,4.982704,3.994715,...,13.112724,14.104104,13.644645,11.725484,11.967791,11.433822,12.062999,9.794262,11.955416,14.020896

In [29]:
# this_file = "../../data/genbank/cut_1_test.csv"
# this_subset.to_csv(this_file, encoding="utf-8")

In [31]:
def cut_csv(ranges, out_name):
    this_range = range(ranges[0], ranges[1])
    this_cut   = endo[endo.columns[[x+4 for x in this_range]]]
    this_subset = meta.join(this_cut, how="outer")
    this_file = "../../data/genbank/final_cuts/" + out_name + ".csv"
    this_subset.to_csv(this_file, encoding="utf-8")

In [32]:
out_names = ["cut_"+str(x) for x in range(1,11)]
out_names

['cut_1',
 'cut_2',
 'cut_3',
 'cut_4',
 'cut_5',
 'cut_6',
 'cut_7',
 'cut_8',
 'cut_9',
 'cut_10']

In [33]:
for index, row in ranges.iterrows():
    print(index)
    cut_csv(list(row), out_names[index])

0
1
2
3
4
5
6
7
8
9